export const apis_data_databases_categories = ["cloud","hosting","version-control"] as const;
export const apis_data_databases_subcategories = ["deploy","learning","management","platforms","providers","resources"] as const;
export const apis_data_databases_tags = ["12-months","ai","alternative","always-free","amazon","api","apis","architecture","astro","atlassian","automation","awesome","aws","azure","backend","beginners","book","books","branching","brands","career","cdn","chat","ci","ci-cd","cli","cloud","code","collaboration","community","components","container","contributions","copilot","course","courses","credit","curated","database","deploy","deployment","design","dev-tools","devops","discovery","distributed","dns","docker","docs","documentation","dual-vcs","edge","education","email","enterprise","examples","extensions","fastapi","fedora","forms","foss","free","free-pack","free-tier","frontend","fullstack","functions","gcp","git","github","gitlab","global","google","guides","hosting","iac","ibm","infra","interactive","interviews","issues","javascript","learning","list","mercurial","microsoft","midudev","monitoring","multi-cloud","nestjs","nextjs","no-cc","nodejs","official","open-source","oracle","paas","pages","patches","pipelines","policies","postgres","postgresql","productivity","programming","public","python","react","real-world","redis","reference","registry","repos","resources","roadmap","security","self-hosted","serverless","skills","snippets","spanish","ssl","static","static-site","storage","students","suite","system-design","tags","team","terraform","terraform-alternative","topics","trending","trial","tutorial","tutorials","typed","typescript","ui","unlimited","utilities","vcs","vercel-alternative","visual","vm","workers"] as const;
export const apis_data_databases_pricing = ['free', 'freemium', 'premium'] as const;
export const apis_data_databases_status = ['active', 'warning', 'deprecated'] as const;
export const apis_data_databases_languages = ["en","es"] as const;

export type CategoryKey = 'cloud' | 'hosting' | 'version-control';
export type SubcategoryKey = 'deploy' | 'learning' | 'management' | 'platforms' | 'providers' | 'resources';
export type TagKey = '12-months' | 'ai' | 'alternative' | 'always-free' | 'amazon' | 'api' | 'apis' | 'architecture' | 'astro' | 'atlassian' | 'automation' | 'awesome' | 'aws' | 'azure' | 'backend' | 'beginners' | 'book' | 'books' | 'branching' | 'brands' | 'career' | 'cdn' | 'chat' | 'ci' | 'ci-cd' | 'cli' | 'cloud' | 'code' | 'collaboration' | 'community' | 'components' | 'container' | 'contributions' | 'copilot' | 'course' | 'courses' | 'credit' | 'curated' | 'database' | 'deploy' | 'deployment' | 'design' | 'dev-tools' | 'devops' | 'discovery' | 'distributed' | 'dns' | 'docker' | 'docs' | 'documentation' | 'dual-vcs' | 'edge' | 'education' | 'email' | 'enterprise' | 'examples' | 'extensions' | 'fastapi' | 'fedora' | 'forms' | 'foss' | 'free' | 'free-pack' | 'free-tier' | 'frontend' | 'fullstack' | 'functions' | 'gcp' | 'git' | 'github' | 'gitlab' | 'global' | 'google' | 'guides' | 'hosting' | 'iac' | 'ibm' | 'infra' | 'interactive' | 'interviews' | 'issues' | 'javascript' | 'learning' | 'list' | 'mercurial' | 'microsoft' | 'midudev' | 'monitoring' | 'multi-cloud' | 'nestjs' | 'nextjs' | 'no-cc' | 'nodejs' | 'official' | 'open-source' | 'oracle' | 'paas' | 'pages' | 'patches' | 'pipelines' | 'policies' | 'postgres' | 'postgresql' | 'productivity' | 'programming' | 'public' | 'python' | 'react' | 'real-world' | 'redis' | 'reference' | 'registry' | 'repos' | 'resources' | 'roadmap' | 'security' | 'self-hosted' | 'serverless' | 'skills' | 'snippets' | 'spanish' | 'ssl' | 'static' | 'static-site' | 'storage' | 'students' | 'suite' | 'system-design' | 'tags' | 'team' | 'terraform' | 'terraform-alternative' | 'topics' | 'trending' | 'trial' | 'tutorial' | 'tutorials' | 'typed' | 'typescript' | 'ui' | 'unlimited' | 'utilities' | 'vcs' | 'vercel-alternative' | 'visual' | 'vm' | 'workers';
export type Pricing = 'free' | 'freemium' | 'premium';
export type Status = 'active' | 'warning' | 'deprecated';
export type Language = 'en' | 'es';
export type SearchFieldKey = 'name' | 'description' | 'tags' | 'category' | 'subcategory';
