export const apis_data_databases_categories = ["cloud","hosting","version-control"] as const;
export const apis_data_databases_subcategories = ["deploy","learning","management","platforms","providers","resources"] as const;
export const apis_data_databases_tags = ["12-months","a-i-cloud-hosting","ai","ai-self-replication","alternative","alucek-gh","alumnium","always-free","amazon","anansi","anthropics","api","apis","architecture","argus","astro","atlassian","automation","awesome","awesome-ai-software-engineering","awesome-autonomous-vehicles","awesome-deep-trading","awesome-open-source-ai","aws","azure","backend","beginners","book","books","branching","brands","bug-bounty","build-nvidia-com","career","cdn","chat","ci","ci-cd","cli","cloud","cloud-management","code","collaboration","community","components","container","contributions","control-de-versiones-repositorios","copilot","course","courses","credit","curated","dark-moon","database","deploy","deployment","design","dev-tools","devops","discovery","distributed","dns","docker","docs","documentation","dual-vcs","edge","education","email","enterprise","examples","extensions","fastapi","fc434091c6414acc098f58b18a0146d8-js","fedora","forms","foss","free","free-pack","free-tier","freecodecamp","frontend","fullstack","functions","gcp","gencad","gimp-mcp","git","github","gitlab","global","globalthreatmap","google","ground-station","guides","hosting","hosting-deploy","iac","ibm","infra","integrate-api-nvidia-com","interactive","interviews","issues","javascript","lazygit","leann","learning","list","live-trade-bench","localstack","management","mercurial","microsoft","midudev","monitoring","multi-cloud","nestjs","nextjs","no-cc","nodejs","official","onyx","open-source","openguider","oracle","paas","pages","patches","pipelines","playtranslate","policies","portless","postgres","postgresql","productivity","programming","public","python","react","reactive-resume","real-world","recursos-github","redis","reference","registry","repos","resources","roadmap","rppg-toolbox","security","self-hosted","serverless","shadowbroker","silicon-studio","skills","snippets","spanish","ssl","static","static-site","storage","students","suite","superserve","system-design","tags","team","terraform","terraform-alternative","timecapsulellm","topics","trending","trial","tutorial","tutorials","typed","typescript","ubuntu-on-android","ui","unlimited","utilities","v0-1-5","vcs","vercel-alternative","vercel-labs-skills","version-control","visual","vm","website-cloner","workers","y-control-de-versiones-repositorios"] as const;
export const apis_data_databases_pricing = ['free', 'freemium', 'premium'] as const;
export const apis_data_databases_status = ['active', 'warning', 'deprecated'] as const;
export const apis_data_databases_languages = ["en","es"] as const;

export type CategoryKey = 'cloud' | 'hosting' | 'version-control';
export type SubcategoryKey = 'deploy' | 'learning' | 'management' | 'platforms' | 'providers' | 'resources';
export type TagKey = '12-months' | 'a-i-cloud-hosting' | 'ai' | 'ai-self-replication' | 'alternative' | 'alucek-gh' | 'alumnium' | 'always-free' | 'amazon' | 'anansi' | 'anthropics' | 'api' | 'apis' | 'architecture' | 'argus' | 'astro' | 'atlassian' | 'automation' | 'awesome' | 'awesome-ai-software-engineering' | 'awesome-autonomous-vehicles' | 'awesome-deep-trading' | 'awesome-open-source-ai' | 'aws' | 'azure' | 'backend' | 'beginners' | 'book' | 'books' | 'branching' | 'brands' | 'bug-bounty' | 'build-nvidia-com' | 'career' | 'cdn' | 'chat' | 'ci' | 'ci-cd' | 'cli' | 'cloud' | 'cloud-management' | 'code' | 'collaboration' | 'community' | 'components' | 'container' | 'contributions' | 'control-de-versiones-repositorios' | 'copilot' | 'course' | 'courses' | 'credit' | 'curated' | 'dark-moon' | 'database' | 'deploy' | 'deployment' | 'design' | 'dev-tools' | 'devops' | 'discovery' | 'distributed' | 'dns' | 'docker' | 'docs' | 'documentation' | 'dual-vcs' | 'edge' | 'education' | 'email' | 'enterprise' | 'examples' | 'extensions' | 'fastapi' | 'fc434091c6414acc098f58b18a0146d8-js' | 'fedora' | 'forms' | 'foss' | 'free' | 'free-pack' | 'free-tier' | 'freecodecamp' | 'frontend' | 'fullstack' | 'functions' | 'gcp' | 'gencad' | 'gimp-mcp' | 'git' | 'github' | 'gitlab' | 'global' | 'globalthreatmap' | 'google' | 'ground-station' | 'guides' | 'hosting' | 'hosting-deploy' | 'iac' | 'ibm' | 'infra' | 'integrate-api-nvidia-com' | 'interactive' | 'interviews' | 'issues' | 'javascript' | 'lazygit' | 'leann' | 'learning' | 'list' | 'live-trade-bench' | 'localstack' | 'management' | 'mercurial' | 'microsoft' | 'midudev' | 'monitoring' | 'multi-cloud' | 'nestjs' | 'nextjs' | 'no-cc' | 'nodejs' | 'official' | 'onyx' | 'open-source' | 'openguider' | 'oracle' | 'paas' | 'pages' | 'patches' | 'pipelines' | 'playtranslate' | 'policies' | 'portless' | 'postgres' | 'postgresql' | 'productivity' | 'programming' | 'public' | 'python' | 'react' | 'reactive-resume' | 'real-world' | 'recursos-github' | 'redis' | 'reference' | 'registry' | 'repos' | 'resources' | 'roadmap' | 'rppg-toolbox' | 'security' | 'self-hosted' | 'serverless' | 'shadowbroker' | 'silicon-studio' | 'skills' | 'snippets' | 'spanish' | 'ssl' | 'static' | 'static-site' | 'storage' | 'students' | 'suite' | 'superserve' | 'system-design' | 'tags' | 'team' | 'terraform' | 'terraform-alternative' | 'timecapsulellm' | 'topics' | 'trending' | 'trial' | 'tutorial' | 'tutorials' | 'typed' | 'typescript' | 'ubuntu-on-android' | 'ui' | 'unlimited' | 'utilities' | 'v0-1-5' | 'vcs' | 'vercel-alternative' | 'vercel-labs-skills' | 'version-control' | 'visual' | 'vm' | 'website-cloner' | 'workers' | 'y-control-de-versiones-repositorios';
export type Pricing = 'free' | 'freemium' | 'premium';
export type Status = 'active' | 'warning' | 'deprecated';
export type Language = 'en' | 'es';
export type SearchFieldKey = 'name' | 'description' | 'tags' | 'category' | 'subcategory';
