export const utilidades_2_cms_categories = ["cms","utilities"] as const;
export const utilidades_2_cms_subcategories = ["dev-tools","general-resources","platforms","seo-scraping"] as const;
export const utilidades_2_cms_tags = ["2025","ai","alerts","alternatives","animation","api","audio","automation","backend","bearnie-dev","blogging","bsky-comments","canvas","cms","codepen","collection","comparison","components","content","css","cv","dark-mode","data","datatype","debugging","design-system","dev","dev-tools","documents","ecommerce","editing","editor","effects","emdash","entertainment","errors","france","free","frontend","ghost","git","git-based","github","government","grid","guide","headless","hosting","ip","javascript","latex","layout","list","logs","lookup","mcp","modals","modern","monitoring","monosketch","nextjs","nodejs","npm","open-source","packages","parallax","pdf","platforms","pretext","publishing","react","realtime","repos","resources","resume","saas","scraping","search","seo","simple","skeleton","spanish","streaming","template","templates","testing-opengraph","theme","tiks","toggle","top","transcription","tutorial","ui","utilities","vanilla","vercel","video","viewer","vps","web-dev","whisper","wordpress","xml-comparator","y-cms-content","y-i-herramientas-dev","y-utilidades-herramientas"] as const;
export const utilidades_2_cms_pricing = ['free', 'freemium', 'premium'] as const;
export const utilidades_2_cms_status = ['active', 'warning', 'deprecated'] as const;
export const utilidades_2_cms_languages = ["en","es","fr"] as const;

export type CategoryKey = 'cms' | 'utilities';
export type SubcategoryKey = 'dev-tools' | 'general-resources' | 'platforms' | 'seo-scraping';
export type TagKey = '2025' | 'ai' | 'alerts' | 'alternatives' | 'animation' | 'api' | 'audio' | 'automation' | 'backend' | 'bearnie-dev' | 'blogging' | 'bsky-comments' | 'canvas' | 'cms' | 'codepen' | 'collection' | 'comparison' | 'components' | 'content' | 'css' | 'cv' | 'dark-mode' | 'data' | 'datatype' | 'debugging' | 'design-system' | 'dev' | 'dev-tools' | 'documents' | 'ecommerce' | 'editing' | 'editor' | 'effects' | 'emdash' | 'entertainment' | 'errors' | 'france' | 'free' | 'frontend' | 'ghost' | 'git' | 'git-based' | 'github' | 'government' | 'grid' | 'guide' | 'headless' | 'hosting' | 'ip' | 'javascript' | 'latex' | 'layout' | 'list' | 'logs' | 'lookup' | 'mcp' | 'modals' | 'modern' | 'monitoring' | 'monosketch' | 'nextjs' | 'nodejs' | 'npm' | 'open-source' | 'packages' | 'parallax' | 'pdf' | 'platforms' | 'pretext' | 'publishing' | 'react' | 'realtime' | 'repos' | 'resources' | 'resume' | 'saas' | 'scraping' | 'search' | 'seo' | 'simple' | 'skeleton' | 'spanish' | 'streaming' | 'template' | 'templates' | 'testing-opengraph' | 'theme' | 'tiks' | 'toggle' | 'top' | 'transcription' | 'tutorial' | 'ui' | 'utilities' | 'vanilla' | 'vercel' | 'video' | 'viewer' | 'vps' | 'web-dev' | 'whisper' | 'wordpress' | 'xml-comparator' | 'y-cms-content' | 'y-i-herramientas-dev' | 'y-utilidades-herramientas';
export type Pricing = 'free' | 'freemium' | 'premium';
export type Status = 'active' | 'warning' | 'deprecated';
export type Language = 'en' | 'es' | 'fr';
export type SearchFieldKey = 'name' | 'description' | 'tags' | 'category' | 'subcategory';
