export const utilidades_2_cms_categories = ["cms","utilities"] as const;
export const utilidades_2_cms_subcategories = ["dev-tools","general-resources","platforms","seo-scraping"] as const;
export const utilidades_2_cms_tags = ["2025","ai","alerts","alternatives","animation","api","audio","audit","automation","awesome","backend","blogging","canvas","cms","codepen","collection","comparison","components","content","crawler","css","curated","cv","dark-mode","data","debugging","design-system","dev","development","discovery","documents","ecommerce","editing","editor","effects","entertainment","errors","france","free","frontend","ghost","git","git-based","github","government","grid","guide","headless","hosting","ip","javascript","latex","layout","list","localhost","logs","lookup","mcp","modals","modern","monitoring","networking","nextjs","nodejs","npm","open-source","optimization","packages","parallax","pdf","performance","publishing","react","realtime","repos","resources","resume","saas","scraping","search","security","seo","simple","skeleton","spanish","streaming","template","templates","theme","toggle","top","transcription","trending","tunnel","tutorial","ui","vanilla","vercel","video","viewer","vps","web","web-dev","whisper","wordpress"] as const;
export const utilidades_2_cms_pricing = ['free', 'freemium', 'premium'] as const;
export const utilidades_2_cms_status = ['active', 'warning', 'deprecated'] as const;
export const utilidades_2_cms_languages = ["en","es","fr"] as const;

export type CategoryKey = 'cms' | 'utilities';
export type SubcategoryKey = 'dev-tools' | 'general-resources' | 'platforms' | 'seo-scraping';
export type TagKey = '2025' | 'ai' | 'alerts' | 'alternatives' | 'animation' | 'api' | 'audio' | 'audit' | 'automation' | 'awesome' | 'backend' | 'blogging' | 'canvas' | 'cms' | 'codepen' | 'collection' | 'comparison' | 'components' | 'content' | 'crawler' | 'css' | 'curated' | 'cv' | 'dark-mode' | 'data' | 'debugging' | 'design-system' | 'dev' | 'development' | 'discovery' | 'documents' | 'ecommerce' | 'editing' | 'editor' | 'effects' | 'entertainment' | 'errors' | 'france' | 'free' | 'frontend' | 'ghost' | 'git' | 'git-based' | 'github' | 'government' | 'grid' | 'guide' | 'headless' | 'hosting' | 'ip' | 'javascript' | 'latex' | 'layout' | 'list' | 'localhost' | 'logs' | 'lookup' | 'mcp' | 'modals' | 'modern' | 'monitoring' | 'networking' | 'nextjs' | 'nodejs' | 'npm' | 'open-source' | 'optimization' | 'packages' | 'parallax' | 'pdf' | 'performance' | 'publishing' | 'react' | 'realtime' | 'repos' | 'resources' | 'resume' | 'saas' | 'scraping' | 'search' | 'security' | 'seo' | 'simple' | 'skeleton' | 'spanish' | 'streaming' | 'template' | 'templates' | 'theme' | 'toggle' | 'top' | 'transcription' | 'trending' | 'tunnel' | 'tutorial' | 'ui' | 'vanilla' | 'vercel' | 'video' | 'viewer' | 'vps' | 'web' | 'web-dev' | 'whisper' | 'wordpress';
export type Pricing = 'free' | 'freemium' | 'premium';
export type Status = 'active' | 'warning' | 'deprecated';
export type Language = 'en' | 'es' | 'fr';
export type SearchFieldKey = 'name' | 'description' | 'tags' | 'category' | 'subcategory';
