export const dns_seguridad_educacion_categories = ["dns-domain","education-learning","security-vpn"] as const;
export const dns_seguridad_educacion_subcategories = ["cybersecurity-learning","dns-services","domain-registrars","programming-courses","security-auth","vpn-services"] as const;
export const dns_seguridad_educacion_tags = ["10gb","500mb","academy","aggregator","ai","angular","apple","articles","auth","authentication","automation","aws","azure","b2b","backend","basics","beginner","best-practices","blockchain","blog","c","career","certification","challenges","cheap","cheatsheet","cisco","cloud","cloudflare","coding","community","comprehensive","computer-science","course","courses","cpp","crypto","cs50","csharp","data","database","ddos","debugging","decentralized","designs","developers","devops","django","dns","docker","docs","documentation","domain","dotnet","dynamic","easy","education","encryption","english","enterprise","eu","exercises","flask","framework","free","frontend","fullstack","game","gcp","git","github","go","golang","google","guide","guides","hardening","harvard","hostname","html","identity","interactive","interview","ios","java","javascript","junior","kubernetes","labs","language","languages","learning","linux","locations","macos","management","mentorship","mern","mfa","microframework","microsoft","ml","modern","mooc","mozilla","multi-tenant","n8n","nextjs","official","open-source","oracle","oscp","pdf","pentesting","php","platform","postgres","practical","practice","preparation","privacy","problems","programming","projects","python","quality","quick","react","reference","registrar","reporting","resources","roadmap","rust","saas","scanner","search","security","server","solidity","spanish","sql","sso","study-plan","subdomain","supabase","swift","sysadmin","technical","technology","tld","tokens","tool","training","tutorial","tutorials","typescript","ui","university","unlimited","various","vercel","visual","visualizer","vpn","vscode","vue","vuejs","warp","web","web3","youtube"] as const;
export const dns_seguridad_educacion_pricing = ['free', 'freemium', 'premium'] as const;
export const dns_seguridad_educacion_status = ['active', 'warning', 'deprecated'] as const;
export const dns_seguridad_educacion_languages = ["en","es"] as const;

export type CategoryKey = 'dns-domain' | 'education-learning' | 'security-vpn';
export type SubcategoryKey = 'cybersecurity-learning' | 'dns-services' | 'domain-registrars' | 'programming-courses' | 'security-auth' | 'vpn-services';
export type TagKey = '10gb' | '500mb' | 'academy' | 'aggregator' | 'ai' | 'angular' | 'apple' | 'articles' | 'auth' | 'authentication' | 'automation' | 'aws' | 'azure' | 'b2b' | 'backend' | 'basics' | 'beginner' | 'best-practices' | 'blockchain' | 'blog' | 'c' | 'career' | 'certification' | 'challenges' | 'cheap' | 'cheatsheet' | 'cisco' | 'cloud' | 'cloudflare' | 'coding' | 'community' | 'comprehensive' | 'computer-science' | 'course' | 'courses' | 'cpp' | 'crypto' | 'cs50' | 'csharp' | 'data' | 'database' | 'ddos' | 'debugging' | 'decentralized' | 'designs' | 'developers' | 'devops' | 'django' | 'dns' | 'docker' | 'docs' | 'documentation' | 'domain' | 'dotnet' | 'dynamic' | 'easy' | 'education' | 'encryption' | 'english' | 'enterprise' | 'eu' | 'exercises' | 'flask' | 'framework' | 'free' | 'frontend' | 'fullstack' | 'game' | 'gcp' | 'git' | 'github' | 'go' | 'golang' | 'google' | 'guide' | 'guides' | 'hardening' | 'harvard' | 'hostname' | 'html' | 'identity' | 'interactive' | 'interview' | 'ios' | 'java' | 'javascript' | 'junior' | 'kubernetes' | 'labs' | 'language' | 'languages' | 'learning' | 'linux' | 'locations' | 'macos' | 'management' | 'mentorship' | 'mern' | 'mfa' | 'microframework' | 'microsoft' | 'ml' | 'modern' | 'mooc' | 'mozilla' | 'multi-tenant' | 'n8n' | 'nextjs' | 'official' | 'open-source' | 'oracle' | 'oscp' | 'pdf' | 'pentesting' | 'php' | 'platform' | 'postgres' | 'practical' | 'practice' | 'preparation' | 'privacy' | 'problems' | 'programming' | 'projects' | 'python' | 'quality' | 'quick' | 'react' | 'reference' | 'registrar' | 'reporting' | 'resources' | 'roadmap' | 'rust' | 'saas' | 'scanner' | 'search' | 'security' | 'server' | 'solidity' | 'spanish' | 'sql' | 'sso' | 'study-plan' | 'subdomain' | 'supabase' | 'swift' | 'sysadmin' | 'technical' | 'technology' | 'tld' | 'tokens' | 'tool' | 'training' | 'tutorial' | 'tutorials' | 'typescript' | 'ui' | 'university' | 'unlimited' | 'various' | 'vercel' | 'visual' | 'visualizer' | 'vpn' | 'vscode' | 'vue' | 'vuejs' | 'warp' | 'web' | 'web3' | 'youtube';
export type Pricing = 'free' | 'freemium' | 'premium';
export type Status = 'active' | 'warning' | 'deprecated';
export type Language = 'en' | 'es';
export type SearchFieldKey = 'name' | 'description' | 'tags' | 'category' | 'subcategory';
