export const dev_ops_testing_translation_categories = ["devops","testing","translation"] as const;
export const dev_ops_testing_translation_subcategories = ["ci-cd","containers","frameworks","load-testing","platforms","tools"] as const;
export const dev_ops_testing_translation_tags = ["accessibility","ai","ai-translation","all-in-one","api","artillery","automated","automation","browsers","browserstack","ci","ci-cd","cloud","collaboration","containers","cross-browser","crowdin","daemonless","deepl","deployment","development","devops","devops-ci-cd","docker","docker-alternative","e2e","edge","enterprise","facebook","fast","frameworks","free","frontend","github","google","gui","ide","javascript","jest","jest-compatible","k6","katalon","kite","kubernetes","lambdatest","learning","legacy","lightweight","lightweight-k8s","load-testing","loader-io","local","localization","localization-platform","locust","lokalise","management","microservices","microsoft","multi-language","open-source","orchestration","performance","pipelines","plugins","podman","poeditor","python","qa","react","releasebot","saucelabs","screenshot-pipeline-qa","security","self-hosted","team","test-cases","test-management","testing","testing-framework","testing-library","testing-platform","testing-tool","testrail","transifex","translation","translation-management","translation-tool","unit-testing","user-testing","vite","vitest","web-testing","workflows","y-devops-ci-cd","yz-testing-qa"] as const;
export const dev_ops_testing_translation_pricing = ['free', 'freemium', 'premium'] as const;
export const dev_ops_testing_translation_status = ['active', 'warning', 'deprecated'] as const;
export const dev_ops_testing_translation_languages = ["en","es"] as const;

export type CategoryKey = 'devops' | 'testing' | 'translation';
export type SubcategoryKey = 'ci-cd' | 'containers' | 'frameworks' | 'load-testing' | 'platforms' | 'tools';
export type TagKey = 'accessibility' | 'ai' | 'ai-translation' | 'all-in-one' | 'api' | 'artillery' | 'automated' | 'automation' | 'browsers' | 'browserstack' | 'ci' | 'ci-cd' | 'cloud' | 'collaboration' | 'containers' | 'cross-browser' | 'crowdin' | 'daemonless' | 'deepl' | 'deployment' | 'development' | 'devops' | 'devops-ci-cd' | 'docker' | 'docker-alternative' | 'e2e' | 'edge' | 'enterprise' | 'facebook' | 'fast' | 'frameworks' | 'free' | 'frontend' | 'github' | 'google' | 'gui' | 'ide' | 'javascript' | 'jest' | 'jest-compatible' | 'k6' | 'katalon' | 'kite' | 'kubernetes' | 'lambdatest' | 'learning' | 'legacy' | 'lightweight' | 'lightweight-k8s' | 'load-testing' | 'loader-io' | 'local' | 'localization' | 'localization-platform' | 'locust' | 'lokalise' | 'management' | 'microservices' | 'microsoft' | 'multi-language' | 'open-source' | 'orchestration' | 'performance' | 'pipelines' | 'plugins' | 'podman' | 'poeditor' | 'python' | 'qa' | 'react' | 'releasebot' | 'saucelabs' | 'screenshot-pipeline-qa' | 'security' | 'self-hosted' | 'team' | 'test-cases' | 'test-management' | 'testing' | 'testing-framework' | 'testing-library' | 'testing-platform' | 'testing-tool' | 'testrail' | 'transifex' | 'translation' | 'translation-management' | 'translation-tool' | 'unit-testing' | 'user-testing' | 'vite' | 'vitest' | 'web-testing' | 'workflows' | 'y-devops-ci-cd' | 'yz-testing-qa';
export type Pricing = 'free' | 'freemium' | 'premium';
export type Status = 'active' | 'warning' | 'deprecated';
export type Language = 'en' | 'es';
export type SearchFieldKey = 'name' | 'description' | 'tags' | 'category' | 'subcategory';
