export const pagos_game_dev_mobile_categories = ["game-dev","mobile","payments"] as const;
export const pagos_game_dev_mobile_subcategories = ["engines","frameworks","jobs","processors"] as const;
export const pagos_game_dev_mobile_tags = ["100-percent","2d","3d","aaa","abstraction","academic-job-search","adalo","agent","aggregator","ai","android","api","apps","awesome-behavioral-interviews","awesome-behavioral-interviews-2","awesome-chatgpt-prompts","awesome-deep-learning","awesome-instagram","awesome-interview-questions","awesome-job-boards","awesome-linkedin","awesome-linkedin-2","awesome-machine-learning","awesome-productivity","awesome-research","babylon","boutique","bubble","buffer-com","builder","capacitor","career-prompts","careerlaunch","challenges","community","construct","direct","drag-drop","elite","evaluated","expo","flexible","flutter","free-tier","freelance","frontend","fullstack","galactic-linkedin-profile-guide","galactic-linkedin-profile-guide-2","game-engine","gdevelop","github-profile-readme-generator","glassdoor-com","glide","global","godot","google-sheets","guide","guide-2","guided","hackerrank-com","hootsuite-com","hybrid","ideas","indeed-com","interview","interviewing-io","ios","javascript","jobs","jobspy","jobspy-2","jsonresume","latam","later-com","lcg","lettergen","library","linkedin-com","linkedin-com-3","linkedin-content-generator","marketplace","matching","micro-saas","mobile","monetizacion-empleo","monetization","mvp","native","network","no-code","open-source","otta-com","outsourcing","overleaf-com","paid","payments","playcanvas","preparation","problems","project-based","pursuit","react","react-native","recommendation-letter-template","remote","remote-first","repo2resume","repo2resume-2","research-internships-for-undergraduates","research-positions","rigorous","scale","search","self-management","senior","serai","shields-io","simplified","simplify-jobs","spanish","startups","stripe","subscription","subscriptions","system-design-interview","taplio-com","teams","tech","tech-interview-handbook","technical","threejs","thunkable","tools","typescript","unity","unreal","validated","verified","visual","web","web-apps","webgl","zero-commission"] as const;
export const pagos_game_dev_mobile_pricing = ['free', 'freemium', 'premium'] as const;
export const pagos_game_dev_mobile_status = ['active', 'warning', 'deprecated'] as const;
export const pagos_game_dev_mobile_languages = ["en","es"] as const;

export type CategoryKey = 'game-dev' | 'mobile' | 'payments';
export type SubcategoryKey = 'engines' | 'frameworks' | 'jobs' | 'processors';
export type TagKey = '100-percent' | '2d' | '3d' | 'aaa' | 'abstraction' | 'academic-job-search' | 'adalo' | 'agent' | 'aggregator' | 'ai' | 'android' | 'api' | 'apps' | 'awesome-behavioral-interviews' | 'awesome-behavioral-interviews-2' | 'awesome-chatgpt-prompts' | 'awesome-deep-learning' | 'awesome-instagram' | 'awesome-interview-questions' | 'awesome-job-boards' | 'awesome-linkedin' | 'awesome-linkedin-2' | 'awesome-machine-learning' | 'awesome-productivity' | 'awesome-research' | 'babylon' | 'boutique' | 'bubble' | 'buffer-com' | 'builder' | 'capacitor' | 'career-prompts' | 'careerlaunch' | 'challenges' | 'community' | 'construct' | 'direct' | 'drag-drop' | 'elite' | 'evaluated' | 'expo' | 'flexible' | 'flutter' | 'free-tier' | 'freelance' | 'frontend' | 'fullstack' | 'galactic-linkedin-profile-guide' | 'galactic-linkedin-profile-guide-2' | 'game-engine' | 'gdevelop' | 'github-profile-readme-generator' | 'glassdoor-com' | 'glide' | 'global' | 'godot' | 'google-sheets' | 'guide' | 'guide-2' | 'guided' | 'hackerrank-com' | 'hootsuite-com' | 'hybrid' | 'ideas' | 'indeed-com' | 'interview' | 'interviewing-io' | 'ios' | 'javascript' | 'jobs' | 'jobspy' | 'jobspy-2' | 'jsonresume' | 'latam' | 'later-com' | 'lcg' | 'lettergen' | 'library' | 'linkedin-com' | 'linkedin-com-3' | 'linkedin-content-generator' | 'marketplace' | 'matching' | 'micro-saas' | 'mobile' | 'monetizacion-empleo' | 'monetization' | 'mvp' | 'native' | 'network' | 'no-code' | 'open-source' | 'otta-com' | 'outsourcing' | 'overleaf-com' | 'paid' | 'payments' | 'playcanvas' | 'preparation' | 'problems' | 'project-based' | 'pursuit' | 'react' | 'react-native' | 'recommendation-letter-template' | 'remote' | 'remote-first' | 'repo2resume' | 'repo2resume-2' | 'research-internships-for-undergraduates' | 'research-positions' | 'rigorous' | 'scale' | 'search' | 'self-management' | 'senior' | 'serai' | 'shields-io' | 'simplified' | 'simplify-jobs' | 'spanish' | 'startups' | 'stripe' | 'subscription' | 'subscriptions' | 'system-design-interview' | 'taplio-com' | 'teams' | 'tech' | 'tech-interview-handbook' | 'technical' | 'threejs' | 'thunkable' | 'tools' | 'typescript' | 'unity' | 'unreal' | 'validated' | 'verified' | 'visual' | 'web' | 'web-apps' | 'webgl' | 'zero-commission';
export type Pricing = 'free' | 'freemium' | 'premium';
export type Status = 'active' | 'warning' | 'deprecated';
export type Language = 'en' | 'es';
export type SearchFieldKey = 'name' | 'description' | 'tags' | 'category' | 'subcategory';
