export const utilidades_1_categories = "utilities" as const;
export const utilidades_1_subcategories = ["fake-data","images-placeholders","productivity"] as const;
export const utilidades_1_tags = ["4m","ai","api","attribution","avatars","bio","business","calendar","cc0","classic","collaboration","complete","contextual","countries","creative","csv","custom","database","dictation","dni","dummy","dynamic","ecommerce","editing","email","fake-data","fast","flexible","food","forms","free","free-tier","fun","generator","google","grammar","hd","high-resolution","images","interactive","javascript","json","knowledge-graph","landing-page","library","license","lightweight","links","lorem-ipsum","markdown","meetings","mock","mockaroo","multi-language","multiple-formats","niche","nie","no-registration","notion-alternative","npm","one-page","open-source","photos","placeholder","presentations","presets","privacy","productivity","products","profiles","psd","public-domain","python","random","research","scheduling","self-hosted","shopify","simple","slides","social-media","spain","spanish","spreadsheet","sql","ssn","stock","surveys","svg","templates","text","tv-shows","unique","unlimited","usa","users","validation","validator","vectors","videos","vintage","voice","web","website","workspace","writing"] as const;
export const utilidades_1_pricing = ['free', 'freemium', 'premium'] as const;
export const utilidades_1_status = ['active', 'warning', 'deprecated'] as const;
export const utilidades_1_languages = ["en","es"] as const;

export type CategoryKey = 'utilities';
export type SubcategoryKey = 'fake-data' | 'images-placeholders' | 'productivity';
export type TagKey = '4m' | 'ai' | 'api' | 'attribution' | 'avatars' | 'bio' | 'business' | 'calendar' | 'cc0' | 'classic' | 'collaboration' | 'complete' | 'contextual' | 'countries' | 'creative' | 'csv' | 'custom' | 'database' | 'dictation' | 'dni' | 'dummy' | 'dynamic' | 'ecommerce' | 'editing' | 'email' | 'fake-data' | 'fast' | 'flexible' | 'food' | 'forms' | 'free' | 'free-tier' | 'fun' | 'generator' | 'google' | 'grammar' | 'hd' | 'high-resolution' | 'images' | 'interactive' | 'javascript' | 'json' | 'knowledge-graph' | 'landing-page' | 'library' | 'license' | 'lightweight' | 'links' | 'lorem-ipsum' | 'markdown' | 'meetings' | 'mock' | 'mockaroo' | 'multi-language' | 'multiple-formats' | 'niche' | 'nie' | 'no-registration' | 'notion-alternative' | 'npm' | 'one-page' | 'open-source' | 'photos' | 'placeholder' | 'presentations' | 'presets' | 'privacy' | 'productivity' | 'products' | 'profiles' | 'psd' | 'public-domain' | 'python' | 'random' | 'research' | 'scheduling' | 'self-hosted' | 'shopify' | 'simple' | 'slides' | 'social-media' | 'spain' | 'spanish' | 'spreadsheet' | 'sql' | 'ssn' | 'stock' | 'surveys' | 'svg' | 'templates' | 'text' | 'tv-shows' | 'unique' | 'unlimited' | 'usa' | 'users' | 'validation' | 'validator' | 'vectors' | 'videos' | 'vintage' | 'voice' | 'web' | 'website' | 'workspace' | 'writing';
export type Pricing = 'free' | 'freemium' | 'premium';
export type Status = 'active' | 'warning' | 'deprecated';
export type Language = 'en' | 'es';
export type SearchFieldKey = 'name' | 'description' | 'tags' | 'category' | 'subcategory';
