export const analytics_monitoring_email_comunicacion_categories = ["analytics","email"] as const;
export const analytics_monitoring_email_comunicacion_subcategories = ["chat-support","error-tracking","monitoring-uptime","notifications-messaging","performance-monitoring","seo-tools","transactional-email","web-analytics"] as const;
export const analytics_monitoring_email_comunicacion_tags = ["alerts","analytics","api","apm","audit","aws","caching","chat","cli","cloud","communication","components","conversational","crawl","crawler","crm","customer-service","dashboards","debugging","email","email-obfuscation","email-transaccional","error-tracking","events","evolution-api-gh","firebase","framework","free","global","google","heatmaps","helpdesk","infrastructure","integration","lightweight","live-chat","logging","logs","marketing","messaging","metrics","microsoft","mjml","mobile","modern","monitoring","no-cookies","nodejs","notificaciones-messaging","notifications","notifications-messaging","npm","omnichannel","on-call","open-source","optimization","performance","privacy","product","pubsub","push","react","real-time","sales","scheduling","scraping","security","seo","session-recording","shared-inbox","sms","status","status-pages","support","ticketing","tracking","transactional","twilio","uptime","verification","voice","web","webhooks","website","websockets","whatsapp","whatsapp-business-platform-web","wordpress","y-email-comunicacia-n"] as const;
export const analytics_monitoring_email_comunicacion_pricing = ['free', 'freemium', 'premium'] as const;
export const analytics_monitoring_email_comunicacion_status = ['active', 'warning', 'deprecated'] as const;
export const analytics_monitoring_email_comunicacion_languages = ["en","es"] as const;

export type CategoryKey = 'analytics' | 'email';
export type SubcategoryKey = 'chat-support' | 'error-tracking' | 'monitoring-uptime' | 'notifications-messaging' | 'performance-monitoring' | 'seo-tools' | 'transactional-email' | 'web-analytics';
export type TagKey = 'alerts' | 'analytics' | 'api' | 'apm' | 'audit' | 'aws' | 'caching' | 'chat' | 'cli' | 'cloud' | 'communication' | 'components' | 'conversational' | 'crawl' | 'crawler' | 'crm' | 'customer-service' | 'dashboards' | 'debugging' | 'email' | 'email-obfuscation' | 'email-transaccional' | 'error-tracking' | 'events' | 'evolution-api-gh' | 'firebase' | 'framework' | 'free' | 'global' | 'google' | 'heatmaps' | 'helpdesk' | 'infrastructure' | 'integration' | 'lightweight' | 'live-chat' | 'logging' | 'logs' | 'marketing' | 'messaging' | 'metrics' | 'microsoft' | 'mjml' | 'mobile' | 'modern' | 'monitoring' | 'no-cookies' | 'nodejs' | 'notificaciones-messaging' | 'notifications' | 'notifications-messaging' | 'npm' | 'omnichannel' | 'on-call' | 'open-source' | 'optimization' | 'performance' | 'privacy' | 'product' | 'pubsub' | 'push' | 'react' | 'real-time' | 'sales' | 'scheduling' | 'scraping' | 'security' | 'seo' | 'session-recording' | 'shared-inbox' | 'sms' | 'status' | 'status-pages' | 'support' | 'ticketing' | 'tracking' | 'transactional' | 'twilio' | 'uptime' | 'verification' | 'voice' | 'web' | 'webhooks' | 'website' | 'websockets' | 'whatsapp' | 'whatsapp-business-platform-web' | 'wordpress' | 'y-email-comunicacia-n';
export type Pricing = 'free' | 'freemium' | 'premium';
export type Status = 'active' | 'warning' | 'deprecated';
export type Language = 'en' | 'es';
export type SearchFieldKey = 'name' | 'description' | 'tags' | 'category' | 'subcategory';
