export const pagos_game_dev_mobile_categories = ["game-dev","mobile","payments"] as const;
export const pagos_game_dev_mobile_subcategories = ["engines","frameworks","jobs","processors"] as const;
export const pagos_game_dev_mobile_tags = ["100-percent","2d","3d","aaa","abstraction","adalo","agent","aggregator","ai","android","api","apps","babylon","boutique","bubble","builder","capacitor","challenges","community","construct","direct","drag-drop","elite","evaluated","expo","flexible","flutter","freelance","free-tier","frontend","fullstack","game-engine","gdevelop","glide","global","godot","google-sheets","guided","hybrid","ideas","interview","ios","javascript","jobs","latam","library","marketplace","matching","micro-saas","mobile","monetization","mvp","native","network","no-code","open-source","outsourcing","paid","payments","playcanvas","preparation","problems","project-based","react","react-native","remote","remote-first","rigorous","scale","search","self-management","senior","simplified","spanish","startups","stripe","subscription","subscriptions","teams","tech","technical","threejs","thunkable","tools","typescript","unity","unreal","validated","verified","visual","web","web-apps","webgl","zero-commission"] as const;
export const pagos_game_dev_mobile_pricing = ['free', 'freemium', 'premium'] as const;
export const pagos_game_dev_mobile_status = ['active', 'warning', 'deprecated'] as const;
export const pagos_game_dev_mobile_languages = ["en","es"] as const;

export type CategoryKey = 'game-dev' | 'mobile' | 'payments';
export type SubcategoryKey = 'engines' | 'frameworks' | 'jobs' | 'processors';
export type TagKey = '100-percent' | '2d' | '3d' | 'aaa' | 'abstraction' | 'adalo' | 'agent' | 'aggregator' | 'ai' | 'android' | 'api' | 'apps' | 'babylon' | 'boutique' | 'bubble' | 'builder' | 'capacitor' | 'challenges' | 'community' | 'construct' | 'direct' | 'drag-drop' | 'elite' | 'evaluated' | 'expo' | 'flexible' | 'flutter' | 'freelance' | 'free-tier' | 'frontend' | 'fullstack' | 'game-engine' | 'gdevelop' | 'glide' | 'global' | 'godot' | 'google-sheets' | 'guided' | 'hybrid' | 'ideas' | 'interview' | 'ios' | 'javascript' | 'jobs' | 'latam' | 'library' | 'marketplace' | 'matching' | 'micro-saas' | 'mobile' | 'monetization' | 'mvp' | 'native' | 'network' | 'no-code' | 'open-source' | 'outsourcing' | 'paid' | 'payments' | 'playcanvas' | 'preparation' | 'problems' | 'project-based' | 'react' | 'react-native' | 'remote' | 'remote-first' | 'rigorous' | 'scale' | 'search' | 'self-management' | 'senior' | 'simplified' | 'spanish' | 'startups' | 'stripe' | 'subscription' | 'subscriptions' | 'teams' | 'tech' | 'technical' | 'threejs' | 'thunkable' | 'tools' | 'typescript' | 'unity' | 'unreal' | 'validated' | 'verified' | 'visual' | 'web' | 'web-apps' | 'webgl' | 'zero-commission';
export type Pricing = 'free' | 'freemium' | 'premium';
export type Status = 'active' | 'warning' | 'deprecated';
export type Language = 'en' | 'es';
export type SearchFieldKey = 'name' | 'description' | 'tags' | 'category' | 'subcategory';
